services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=mydb         
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes: 
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - influxdb
    networks:
      - monitoring

  jmeter:
    image: justb4/jmeter:5.5
    container_name: jmeter
    depends_on:
      - influxdb
    volumes:
      - ./jmeter-test-plan:/jmeter-test-plan
      - ./plugins/jmeter-plugins-influxdb2-listener-2.8.jar:/opt/apache-jmeter/lib/ext/jmeter-plugins-influxdb2-listener.jar
    command: >
      -n -t /jmeter-test-plan/jmeter_configs.jmx 
      -JinfluxDBUrl=http://localhost:8086
      -JinfluxDBDb=mydb
      -JinfluxDBUser=admin
      -JinfluxDBPassword=adminpassword

volumes:
  influxdb_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
